info:
  contact: {}
  license: {}
paths:
  /account/Signup:
    post:
      consumes:
      - application/json
      description: It will register new users if the post data provided properly.
      operationId: Signup-new-account
      parameters:
      - description: FullName
        in: body
        name: fullname
        required: true
        schema:
          type: string
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      responses:
        "201":
          description: Account is created
        "250":
          description: An account with this email already exists
        "400":
          description: Invalid signup parameters
      summary: Signup an account
swagger: "2.0"
