info:
  contact: {}
  license: {}
paths:
  /account/signup:
    post:
      consumes:
      - application/json
      description: It will register new users if the post data provided properly.
      operationId: signup-new-account
      parameters:
      - description: FullName
        in: body
        name: fullName
        required: true
        schema:
          type: string
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: ActivationCode
        in: body
        name: activationCode
        required: true
        schema:
          type: string
      responses:
        "201":
          description: Account is created
      summary: Signup an account test
swagger: "2.0"
